### ISSUE TITLE
Can't connect if the password contain "@" 

### ISSUE THREAD

**Issue by Louis-Tian** [mapr/maprdb-python-client#61]
The currently implementation of parsing connection string is flawed. If the password contains `@`, the parsing will result `ValueError`.

https://github.com/mapr/maprdb-python-client/blob/db556d8bca93552567ec69fe2bea89f9c52502ab/mapr/ojai/storage/OJAIConnection.py#L101

Suggestion using regex that allows user to escape`@` inside the password instead of the naive `split` method

**Comment by dshylov** [comment]
@Louis-Tian thanks for notation.
I'll fix it soon.
